days = 60 #how far back to look for bases. Suggested at least 14
skip = 12 #this is how many candles back from now we ignore when scanning for bases; has to be at least 7
minutes = "60" #candle time interval. suggested 60 for regular base breaks
drop = .95 #percentage below detected bases to set alert so .96 is 4% down. Suggest at least .96 or .95
six_candle_up = 1.08 #how much higher the sixth candles from the base should be relative to the base. Suggested at least 1.05
sensitivity = 3 #A number 0-6 for how sensitive the scanner is to quality bases. Lower number allows higher quality bases but less of them. 1, 2, or 3 seem to work best
low_or_close = 3 #whether you want bases based on the low or the close (bottom of wick or candle respectively). 3 gives you low and 4 is close. (Also 0 is open and 1 is high if you want to go there)
split_the_difference = False #Detects bases at 50% of wicks rather than the low or close prices. Setting this to True will cause the low_or_close variable to be ignored
delete_old_alerts = True #If you want to delete all old alerts in alerts_set.txt for a coin before creating a new alert for that coin
exchange = "BTRX"
minimum_volume = 1 #Filters out all coins whose volume (in base coin in the last 24h) is less than this amount
market = "BTC"
